name: Node.js CI

on:
  push:
    branches: [ updated ]
  pull_request:
    branches: [ updated ]

jobs:
  bulid:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run:
          npm i
          npm start